import { useState } from 'react';
import { Volume2,Square,Leaf,BookOpen,Headphones,PenLine,Mic,Languages } from './icons';
import { zh as t } from '../i18n/zh';
import type { WeeklyLesson } from '../data/types';
import type { Garden } from '../hooks/useGarden';
import { dateKey,updateReview } from '../utils/learning';
import { useSpeech } from '../hooks/useSpeech';
import { Quiz } from './Quiz';
import { Recorder } from './Recorder';
import { request } from '../server';
import { SkillTabs } from './SkillTabs';
export type Skill='vocabulary'|'reading'|'listening'|'grammar'|'writing'|'speaking';
const skills=[['vocabulary',t.vocab,Leaf],['listening',t.listening,Headphones],['reading',t.reading,BookOpen],['grammar',t.grammar,Languages],['writing',t.writing,PenLine],['speaking',t.speaking,Mic]] as const;
export function Classroom({lesson,garden,initialSkill='vocabulary'}:{lesson:WeeklyLesson;garden:Garden;initialSkill?:Skill}){
 const [skill,setSkill]=useState<Skill>(initialSkill),[showText,setShowText]=useState(false),[wordIndex,setWordIndex]=useState(0),[flipped,setFlipped]=useState(false),[feedback,setFeedback]=useState(''),[busy,setBusy]=useState(false),[task,setTask]=useState<'task1'|'task2'>('task2');
 const speech=useSpeech();const {state,update,auth}=garden;
 const key=`${lesson.week}.${skill}`; const draftKey=`${key}.${skill==='writing'?task:'transcript'}`;
 const draft=state.notes[draftKey]??'';
 function result(r:{correct:number;total:number;wrongIds:string[]}){update(prev=>({...prev,attempts:{...prev.attempts,[key]:{...r,date:dateKey()}}}));}
 const dueWords=lesson.vocabulary.filter(word=>!state.reviews[word.word]||state.reviews[word.word].due<=dateKey());
 const word=dueWords[wordIndex%dueWords.length];
 async function ai(){
  if(!auth){setFeedback(t.aiOff);return;}if(draft.trim().length<20){setFeedback('请先完成一段至少 20 字符的独立作品。');return;}
  setBusy(true);setFeedback('');try{const data=await request<{feedback:string}>('/api/ai-feedback',auth.token,{kind:skill==='writing'?'writing':'speaking',text:draft,prompt:skill==='writing'?lesson.writing[task]:lesson.speaking.part2});setFeedback(data.feedback);}catch(e){setFeedback((e as Error).message);}finally{setBusy(false);}
 }
 return <div className="stack gap-5"><SkillTabs items={skills} value={skill} disabled={busy} onChange={id=>{setSkill(id);setFeedback('');speech.stop();}}/>
  <div className="paper classroom-paper" id="classroom-panel" role="tabpanel" aria-labelledby={`skill-tab-${skill}`} tabIndex={0}><div className="row justify-between"><span className="eyebrow">WEEK {String(lesson.week).padStart(2,'0')} · {lesson.level}</span><span className="tag">原创课程</span></div>
  {skill==='vocabulary'&&<><h2>{t.vocab}</h2><p className="muted">{dueWords.length} 张待复习 · 先回忆，再翻面。</p>{word?<><button className={'flashcard '+(flipped?'flipped':'')} onClick={()=>setFlipped(!flipped)} aria-label={t.wordFlip}><span className="card-kicker">{flipped?word.partOfSpeech:t.wordFlip}</span><strong>{flipped?word.meaning:word.word}</strong><span className="english">{word.example}</span><span className="flash-decoration">✧</span></button><div className="row justify-center flex-wrap"><button className="button secondary" onClick={()=>speech.speak(word.word)}><Volume2 size={17}/>{t.speak}</button>{[false,true].map(remembered=><button className={'button '+(remembered?'primary':'secondary')} key={String(remembered)} onClick={()=>{update(prev=>({...prev,reviews:{...prev.reviews,[word.word]:updateReview(prev.reviews[word.word],remembered)}}));setFlipped(false);setWordIndex(0);}}>{remembered?t.remember:t.forget}</button>)}</div><p className="muted">{t.materialsNote}</p></>:<div className="empty-state"><Leaf size={40}/><h3>{t.emptyReview}</h3><button className="button secondary" onClick={()=>{const words=lesson.vocabulary.map(w=>w.word);update(prev=>({...prev,reviews:Object.fromEntries(Object.entries(prev.reviews).filter(([w])=>!words.includes(w)))}));}}>{t.retry}</button></div>}</>}
  {(skill==='reading'||skill==='listening')&&<><h2>{lesson[skill].title}</h2>{skill==='listening'&&<><p className="muted">{t.ttsNote}</p><div className="row flex-wrap mb-4"><button className="button primary" onClick={()=>speech.speaking?speech.stop():speech.speak(lesson.listening.text)}>{speech.speaking?<Square size={16}/>:<Volume2 size={16}/>} {speech.speaking?t.stopSpeak:t.speak}</button><button className="button secondary" onClick={()=>setShowText(!showText)}>{showText?t.hideText:t.showText}</button></div></>}{(skill==='reading'||showText)&&<article className="reading-text english">{lesson[skill].text.split('\n').map((para,i)=><p key={i}>{para}</p>)}</article>}<Quiz key={key} title="读懂信息，再回答问题" questions={lesson[skill].questions} savedAnswers={state.answers[key]??{}} onAnswers={answers=>update(prev=>({...prev,answers:{...prev.answers,[key]:answers}}))} onResult={result}/></>}
  {skill==='grammar'&&<><h2>{lesson.grammar.title}</h2><p className="instruction">{lesson.grammar.explanation}</p><div className="example-list">{lesson.grammar.examples.map(example=><p key={example} className="english">{example}</p>)}</div><Quiz key={key} questions={lesson.grammar.questions} savedAnswers={state.answers[key]??{}} onAnswers={answers=>update(prev=>({...prev,answers:{...prev.answers,[key]:answers}}))} onResult={result}/></>}
  {skill==='writing'&&<><h2>{t.writing} · 把想法说清楚</h2><div className="row mb-4"><button className={'pill '+(task==='task1'?'active':'')} disabled={busy} onClick={()=>{setTask('task1');setFeedback('');}}>{t.task1}</button><button className={'pill '+(task==='task2'?'active':'')} disabled={busy} onClick={()=>{setTask('task2');setFeedback('');}}>{t.task2}</button></div><p className="prompt-box english">{lesson.writing[task]}</p><label className="field-label" htmlFor="writing-draft">{t.draft}<span>{draft.trim()?draft.trim().split(/\s+/).length:0} {t.wordsCount}</span></label><textarea id="writing-draft" className="draft english" maxLength={12000} value={draft} placeholder={t.draftPlaceholder} onChange={e=>update(prev=>({...prev,notes:{...prev.notes,[draftKey]:e.target.value}}))}/><p className="muted">{garden.status} · {t.aiDisclaimer}</p><button className="button primary" disabled={busy} onClick={ai}><PenLine size={17}/>{busy?'正在分析…':t.askAI}</button><p className="muted">提交后，正文与题目将发送至服务器配置的 AI 服务商。</p></>}
  {skill==='speaking'&&<><h2>{t.speaking} · 让声音长出勇气</h2><div className="speaking-questions"><h3>Part 1 · 聊聊日常</h3>{lesson.speaking.part1.map(q=><p key={q} className="english">{q}</p>)}<h3>Part 2 · 一分钟准备</h3><p className="prompt-box english">{lesson.speaking.part2}</p><h3>Part 3 · 再想深一点</h3>{lesson.speaking.part3.map(q=><p key={q} className="english">{q}</p>)}</div><Recorder token={auth?.token} title={`week-${lesson.week}-speaking`}/><label className="field-label mt-5" htmlFor="transcript">{t.transcript}</label><textarea id="transcript" className="draft english" value={draft} maxLength={12000} placeholder="把自己说的内容手动转写在这里，先找一处可以说得更清楚的地方。" onChange={e=>update(prev=>({...prev,notes:{...prev.notes,[draftKey]:e.target.value}}))}/><button className="button primary" disabled={busy} onClick={ai}>{busy?'正在分析…':t.askAI}</button></>}
  {speech.error&&<p className="notice" role="status">{speech.error}</p>}
  {feedback&&<section className="feedback" role="status"><h3>{t.ai}</h3><p className="muted">{t.aiDisclaimer}</p><div className="pre-line">{feedback}</div></section>}
  </div></div>;
}
