import { useRef,useState } from 'react';
import { ArrowUp,ArrowDown,Download,Upload,Check,Palette } from 'lucide-react';
import { zh as t } from '../i18n/zh';
import type { Garden } from '../hooks/useGarden';
import { validateImport,type LearningState } from '../utils/learning';
export type Preferences={theme:string;density:string;font:string;motion:string;order:string[]};
export const defaults:Preferences={theme:'garden',density:'comfortable',font:'normal',motion:'full',order:['tasks','timer','growth','note']};
const themes=[['garden',t.garden,'#53795e','#eff4ec'],['cream',t.cream,'#b9854c','#fbf4e9'],['rose',t.rose,'#b8667d','#fff1f3'],['ocean',t.ocean,'#43868f','#eaf5f8'],['night',t.night,'#a8c69d','#17252c']];
export function Settings({prefs,setPrefs,garden}:{prefs:Preferences;setPrefs:(value:Preferences)=>void;garden:Garden}){
 const file=useRef<HTMLInputElement>(null),[message,setMessage]=useState(''),[pending,setPending]=useState<LearningState|null>(null);
 const names:Record<string,string>={tasks:t.checklist,timer:t.timer,growth:t.progress,note:t.note};
 function backup(state=garden.state){const blob=new Blob([JSON.stringify({version:1,state},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='english-garden-progress.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <div className="settings-grid"><section className="paper"><div className="row"><Palette size={21}/><h2>{t.themes}</h2></div><p className="muted">喜欢哪种风格，就让花园变成哪种样子。{t.device}</p><div className="theme-grid">{themes.map(([key,label,accent,bg])=><button key={key} className={'theme-choice '+(prefs.theme===key?'selected':'')} onClick={()=>setPrefs({...prefs,theme:key})}><span className="theme-preview" style={{background:bg,color:accent}}><span/><span/><span/>{prefs.theme===key&&<Check size={20}/>}</span><strong>{label}</strong></button>)}</div></section>
 <section className="paper"><h2>{t.layouts}</h2><p className="muted">调整首页模块的顺序，先看到你最关心的内容。</p>{prefs.order.map((key,i)=><div key={key} className="order-row"><span>{names[key]}</span><div className="row"><button className="icon-button" aria-label={`${names[key]}${t.moveUp}`} disabled={i===0} onClick={()=>{const order=[...prefs.order];[order[i-1],order[i]]=[order[i],order[i-1]];setPrefs({...prefs,order});}}><ArrowUp size={17}/></button><button className="icon-button" aria-label={`${names[key]}${t.moveDown}`} disabled={i===prefs.order.length-1} onClick={()=>{const order=[...prefs.order];[order[i],order[i+1]]=[order[i+1],order[i]];setPrefs({...prefs,order});}}><ArrowDown size={17}/></button></div></div>)}</section>
 <section className="paper"><h2>让页面更舒服</h2>{[['density',t.density,[['comfortable',t.comfortable],['compact',t.compact]]],['font',t.font,[['normal','标准'],['large','大字']]],['motion',t.animation,[['full',t.motionFull],['low',t.motionLow],['none',t.motionNone]]]].map(([key,label,options])=><div className="setting-field" key={key as string}><h3>{label as string}</h3><div className="row flex-wrap">{(options as string[][]).map(([value,name])=><button key={value} className={'pill '+(prefs[key as 'density'|'font'|'motion']===value?'active':'')} onClick={()=>setPrefs({...prefs,[key as string]:value})}>{name}</button>)}</div></div>)}<button className="button secondary mt-4" onClick={()=>setPrefs(defaults)}>{t.reset}</button></section>
 <section className="paper"><h2>计划与学习记录</h2><label className="field-label" htmlFor="start-date">{t.startDate}</label><input id="start-date" type="date" value={garden.state.startDate} onChange={e=>garden.update(prev=>({...prev,startDate:e.target.value}))}/><label className="field-label mt-4" htmlFor="nickname">{t.nickname}</label><input id="nickname" value={garden.state.nickname} maxLength={30} onChange={e=>garden.update(prev=>({...prev,nickname:e.target.value}))}/><div className="row flex-wrap mt-5"><button className="button secondary" onClick={()=>backup()}><Download size={17}/>{t.export}</button><button className="button secondary" onClick={()=>file.current?.click()}><Upload size={17}/>{t.import}</button><input hidden type="file" accept="application/json,.json" ref={file} onChange={async e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>2000000){setMessage('文件超过 2 MB，无法导入');return;}const parsed=validateImport(await f.text());if(!parsed.ok||!parsed.state){setMessage('这不是有效的学习备份');return;}setPending(parsed.state);e.target.value='';}}/></div>{pending&&<div className="notice"><p>{t.restoreWarning}</p><div className="row"><button className="button primary" onClick={()=>{garden.update(()=>pending);setPending(null);setMessage('记录已恢复');}}>{t.confirmImport}</button><button className="button secondary" onClick={()=>setPending(null)}>{t.cancel}</button></div></div>}{message&&<p role="status">{message}</p>}<p className="muted">{garden.status}</p>{garden.auth&&<button className="button secondary" onClick={()=>garden.retrySync().then(()=>setMessage('同步已完成')).catch(e=>setMessage(e.message))}>重试同步</button>}{garden.recovery&&<div className="notice"><h3>发现尚未同步的记录</h3><p>其他设备可能已更新云端。请先导出备份，再选择要保留的版本；恢复会替换当前云端记录。</p><div className="row flex-wrap"><button className="button secondary" onClick={()=>backup(garden.recovery!)}>导出未同步备份</button><button className="button primary" onClick={()=>{if(confirm('确认用这份未同步备份替换云端记录？'))void garden.restorePending().catch(e=>setMessage(e.message));}}>恢复未同步备份</button><button className="button secondary" onClick={()=>{if(confirm('确认放弃未同步备份并保留云端记录？请先导出需要的作品。'))void garden.keepCloud().catch(e=>setMessage(e.message));}}>保留云端记录</button></div></div>}</section></div>;
}
