import { useEffect,useState } from 'react';
import { Heart,Send,RefreshCw,Lock,Trash2,Headphones } from './icons';
import { zh as t } from '../i18n/zh';
import { request,recordingUrl } from '../server';
import type { Garden } from '../hooks/useGarden';
type Space={users:{id:string;displayName:string;state:{completed?:number[]}}[];messages:{id:number;userId:string;displayName:string;text:string;createdAt:string}[]};
type Recording={id:string;userId:string;title:string;shared:boolean;createdAt:string};
export function Together({garden,openLogin}:{garden:Garden;openLogin:()=>void}){
 const [space,setSpace]=useState<Space|null>(null),[message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[recordings,setRecordings]=useState<Recording[]>([]),[audio,setAudio]=useState('');
 const token=garden.auth?.token;
 async function refresh(){if(!token)return;try{const [s,r]=await Promise.all([request<Space>('/api/space',token),request<{recordings:Recording[]}>('/api/recordings',token)]);setSpace(s);setRecordings(r.recordings);setError('');}catch(e){setError((e as Error).message);}}
 useEffect(()=>{refresh();if(!token)return;const id=setInterval(refresh,30000);return()=>clearInterval(id);},[token]);
 useEffect(()=>()=>{if(audio)URL.revokeObjectURL(audio);},[audio]);
 if(!token)return <section className="paper empty-state"><div className="empty-heart"><Heart size={42}/></div><h2>一起走，比走得快更重要。</h2><p>{t.noPartner}</p><p className="muted">这里不放模拟搭档和虚假留言。</p><button className="button primary" onClick={openLogin}><Lock size={17}/>{t.login}</button></section>;
 return <div className="stack gap-5"><section className="paper"><div className="row justify-between"><h2>你们的两人空间</h2><button className="icon-button" aria-label="刷新两人空间" onClick={refresh}><RefreshCw size={18}/></button></div><div className="partner-grid">{space?.users.map((u,i)=><div className="partner-card" key={u.id}><div className={'avatar avatar-'+i}>{u.displayName.slice(0,1)}</div><strong>{u.displayName}</strong><span>{u.state.completed?.length??0} 个学习日</span><div className="progress-track"><i style={{width:`${(u.state.completed?.length??0)/336*100}%`}}/></div></div>)}</div></section>
 <section className="paper"><h2>{t.message}</h2><form onSubmit={async e=>{e.preventDefault();if(!message.trim()||busy)return;setBusy(true);try{await request('/api/messages',token,{text:message});setMessage('');await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><textarea value={message} maxLength={1000} placeholder={t.messagePlaceholder} onChange={e=>setMessage(e.target.value)}/><div className="row justify-between mt-3"><span className="muted">{message.length}/1000</span><button className="button primary" disabled={!message.trim()||busy}><Send size={17}/>{t.send}</button></div></form><div className="message-wall">{space?.messages.length?space.messages.map(m=><article className="message" key={m.id}><div className="row justify-between"><strong>{m.displayName}</strong><time>{new Date(m.createdAt).toLocaleString('zh-CN')}</time></div><p className="pre-line">{m.text}</p></article>):<p className="muted">{t.noMessages}</p>}</div></section>
 <section className="paper"><h2>{t.recordings}</h2><p className="muted">录音默认私有。手动分享后，搭档才能播放。</p>{audio&&<audio controls src={audio}/>}<div className="stack">{recordings.map(r=><div className="recording-row" key={r.id}><div><strong>{r.title}</strong><p className="muted">{r.shared?'已分享给搭档':'仅本人可见'}</p></div><div className="row flex-wrap"><button className="icon-button" aria-label={`播放 ${r.title}`} onClick={async()=>{try{setAudio(await recordingUrl(token,r.id));}catch(e){setError((e as Error).message);}}}><Headphones size={17}/></button>{String(r.userId)===String(garden.auth?.user.id)&&<><button className="pill" onClick={async()=>{try{await request(`/api/recordings/${r.id}`,token,{shared:!r.shared},'PATCH');await refresh();}catch(e){setError((e as Error).message);}}}>{r.shared?'取消分享':t.share}</button><button className="icon-button" aria-label={`删除 ${r.title}`} onClick={async()=>{if(!confirm('删除这段录音？'))return;try{await request(`/api/recordings/${r.id}`,token,undefined,'DELETE');await refresh();}catch(e){setError((e as Error).message);}}}><Trash2 size={17}/></button></>}</div></div>)}</div></section>{error&&<p className="notice" role="alert">{error}</p>}</div>;
}
